version: '3.8'

services:
  cv-back:
    container_name: CV-back
    build:
      context: ./CV-back
    networks:
      - cv-reseau

  cv-front:
    container_name: CV-front
    build:
      context: ./CV-front
    networks:
      - cv-reseau
    ports:
      - "80:8080"

  db:
    image: postgres:16
    container_name: db-cv
    restart: always
    environment:
      POSTGRES_USER: samuel
      POSTGRES_PASSWORD: iwantmyjob
      POSTGRES_DB: CvData
    volumes:
      - ./data:/var/lib/postgresql/data
    networks:
      - cv-reseau
    expose:
      - "5432"

networks:
  cv-reseau:
    external: true
